[package]
name = "hist-sparse"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }

[dependencies]
hist-axes = { workspace = true }
hist = { workspace = true }
anyhow = { workspace = true }
